---
title: "Systeem Biodanza"
output:
    html_document:
        code_download: false
        toc: false
        number_sections: false
        code_folding: "none"
---

Biodanza maakt gebruik van de kracht van muziek, dans en beweging in groep om tot een beleving (vivencia) te komen. Dat brengt positieve veranderingsprocessen op gang die door kunnen werken in ons dagdagelijkse leven. Jezelf en de ander ontmoeten staat in Biodanza centraal. Om tot een beleving te komen is het belangrijk dat we ons veilig voelen in de groep. We staan open voor elkaar zonder oordeel.

Biodanza is Gym voor je hele zijn en

- laat je opnieuw verbinden met jezelf, de anderen en het universum (menselijke integratie), 
- het verbetert de algemene energie en stimuleert je organisme en cellen zich opnieuw te vernieuwen (vernieuwing van het organisme),
- inspireert je om warmte en affectiviteit opnieuw in de wereld te zetten (affectieve heropvoeding), en,
- laat je weer voeling krijgen met je oorspronkelijke manier van zijn (oorspronkelijke manier van leven).


### Menselijke integratie

In ons moderne leven hebben we soms maar weinig voeling met alle leven dat ons omringt. Net alsof we de voeling met onze instincten wat verloren zijn. Een soort verzwakking ervan. Dat is anders bij de mens dan bij planten en dieren. De zonnebloem draait zijn hart naar het licht, De kat spint en rekt zich in het lang en breed uit, de spin weeft zijn web,… Wij mensen zetten vaak ons hoofd boven ons hart. Terwijl we ons hoofd mogen laten zakken in ons hart, zodat lichaam en geest één kunnen worden.  

In de Biodanza stimuleren we de verbondenheid met het leven. Het is een integratieproces van ons menselijke zijn die in gang wordt gezet. Je groeit in het terug verbinden met jezelf. Lichaam en geest komen in evenwicht en kunnen weer als één ervaren worden. Daarnaast is ook de verbinding met andere mensen heel belangrijk in de Biodanza. Wie we zijn kan pas geopenbaard worden door de ander. Die andere vertelt wie we zijn. Hoe oprechter dit gebeurt, hoe intenser we dat kunnen ervaren. De kracht van Biodanza zit in het wij , ik ben jij, ik ben deel van jouw. Elke oefening is in feite een voorbereiding op de ontmoeting. Ten slotte versterkt Biodanza ook de ervaring van jezelf als deel van een groter geheel. De band herstellen en voelen die ons verbindt met de natuur. Het universum. We zijn een schakel in het grote geheel. Alles maakt deel uit van een groter geheel. De mensen, dieren, planten, stenen, sterren, de oceaan… Alles wat leeft. En leven zit overal in. We zijn een eenheid, een hartenklop in het groter geheel.  

Het is fijn te mogen ervaren om terug contact te kunnen maken met alles dat is. Deze functies te kunnen herstellen. Want als we onszelf, de ander en de kosmos kunnen integreren, dan kunnen we pas voelen dat we echt leven. Op den duur kan je het ervaren als een echte levenshouding. Waardoor we weer in contact komen met onze oorsprong. We zijn samen onderweg te worden wie we in oorsprong zijn. We zijn een onafgewerkt gedicht. Dansen in groep kan het gedicht verrijken.  

Om dit alles te kunnen integreren is herhaling heel belangrijk. Fijn om samen in de wekelijkse bijeenkomst te kunnen oefenen, groeien en bloeien. Om samen het leven te dansen.  
  
  
  
### Vernieuwing van het organisme

Het samen functioneren kan best wel complex zijn. We zijn altijd maar op zoek naar oplossingen, passen ons aan om een evenwicht te ervaren. Dat is heel normaal. Oplossingen liggen er niet voor het grijpen, liggen niet zomaar vast. We hebben dan ook in zekere mate de keuze hoe we ons gedragen in een bepaalde situatie. Maar veranderingen en het zoeken van nieuwe evenwichten geeft ons vaak spanning, stress, is soms chaos,…  

Er zijn verschillende systemen om uit de chaos te raken…één daarvan is de liefde en Biodanza is net ontstaan uit nostalgie naar de liefde zegt Rolando Toro zelf. En dan kunnen we vanuit de chaos een nieuw evenwicht bereiken en ons vernieuwen.  

Die vernieuwing van onze cellen en ons volledige organisme wordt door Biodanza gestimuleerd door de zelfregulerende processen in ons lichaam te versterken. Door omgevingsfactoren ontstaan er bijvoorbeeld schommelingen in onze hormonen (honger, emoties door gebeurtenissen,…), onze zelf regulerende processen proberen daarin een evenwicht te vinden en te bewaren. Dat evenwicht is dynamisch met schommelingen binnen bepaalde grenzen die groei en vernieuwing stimuleren. Biodanza zorgt er ook voor dat stressfactoren teruggedrongen worden waardoor de zelfregulerende processen worden versterkt en de schommelingen zo verkleinen. Bijvoorbeeld als er iets gebeurt op je pad die je uit evenwicht brengt dan kunnen we onder stress volledig overspoelt raken. In situaties waarin je minder stress hebt en in contact bent met jezelf en met alles rondom je. Dan kan je eenzelfde gebeurtenis dikwijls beter dragen.  

Het vernieuwen van het organisme binnen Biodanza wordt gestimuleerd door oefeningen die ons terug naar de kindertijd brengen. Oefeningen die de lichamelijke omstandigheden uit de prille babytijd bij ons naar boven brengen. Zelfs tot terug in de baarmoeder. Je kan dan een diepe genegenheid voelen voor de persoon die je “containt”, je bescherming geeft. Je opent je voor een nieuwe levensstijl, je ontdekt nieuwe redenen om te leven. Je voelt dat angst en stress verminderen. Het naar boven halen van deze omstandigheden zorgt ervoor dat veel meer energie door het lichaam kan worden gespendeerd in de vernieuwing van het organisme waardoor het veel sneller herstelt.

### De affectieve heropvoeding

Biodanza vertrekt altijd vanuit warmte en genegenheid. Het belangrijkste doel in Biodanza is het stimuleren van de affectiviteit. Het is belangrijk om je in het hart van een ander te kunnen plaatsen. Biodanza kan je niet alleen beleven. Het is enkel mogelijk om tot een vivencia te komen samen met andere mensen. Een groep waar de veiligheid aanwezig is, er niet geoordeeld wordt. Een groep die affectief en geïntegreerd is. Om zo in alle veiligheid elkaar op verschillende manieren te kunnen ontmoeten, met elkaar via het lichaam te communiceren. Het Biodanza systeem staat open voor de gemeenschap. Er is een grote tolerantie voor de mensheid zoals die is, zonder discriminatie van ras, sekse, leeftijd. We staan open voor elkaar zonder oordeel. Iedereen mag zijn. Zonder masker of zonder een rol te spelen gaan we op ontdekking naar ons ware zijn. In het hier en nu. Een gemeenschap van verbondenheid. We kijken om ons heen en ontmoeten de ander in zijn zijn en ontmoeten via de ander terug onszelf. De lichamelijke ervaring is hier belangrijk, het geeft en ontvangt. Het is geen competitie. Anders ga je weg van je eigen schoonheid.
Die warmte en genegenheid neem je uit de Biodanza sessies mee in het dagdagelijkse leven waardoor je ook van hieruit jezelf en je omgeving gaat transformeren.

## De oorspronkelijke manier van leven opnieuw leren

We verlangen allemaal naar harmonie in ons leven. Dat is eigen aan ons mens zijn. Maar als we harmonie wil ervaren is het belangrijk om je te verbinden met je instincten en daar trouw aan te zijn. We zijn dat wat verleerd. Het is belangrijk om er opnieuw gevoelig voor te worden. Instincten hoeven niet aangeleerd te worden. We zijn ermee geboren. Ze moeten dus enkel weer geactiveerd worden.
Het oorspronkelijk doel van onze instincten is om ons aan te kunnen passen aan de omgeving wat belangrijk is om te kunnen overleven. Hoe minder we onze instincten nodig hebben, hoe meer dat de kracht ervan afneemt. Dat voelen we vaak in ons dagelijkse leven. Heel vaak weten we het niet, voelen we niet, wat er ons te doen staat. Het westen heeft een scheiding gemaakt tussen lichaam en geest waardoor we de boodschappen van het lichaam niet kunnen beluisteren…vaak tot we pijn hebben.
De weg om terug bewust voor onze instincten open te staan is belangrijker dan het doel. Je gaat je hoofd niet uitschakelen maar je hoofd selectief gebruiken. Dan kan je de controle loslaten en voelen dat het leven stroomt als een rivier. Deze aangeboren impulsen gebruiken als onderdeel van je levensstijl, is een natuurlijke manier om op harmonische wijze om te gaan met je lichamelijke behoeften en zo je gezondheid te behouden. De instincten vertegenwoordigen de natuur in ons. Als we hier gevoeliger voor worden dan herstellen we de band tussen natuur en cultuur.
In Biodanza omarmen we het idee dat onze gezondheid verbonden is met de bron van het leven. Het stimuleert moed en plezier in het leven om binnen een affectief geïntegreerde groep de ontwikkeling van de oorspronkelijke manier van leven, opnieuw te leren.

[Wekelijkse Groep Biodanza](http://www.n-zicht.be/wekelijkse-groep-biodanza/)  

[Getuigenissen](./getuigenissen.html)
